### PR TITLE
Fixed case sensitive issue add_personnel function

### PR DESCRIPTION
**Pull request by ErinCain**

### CODE REVIEW

**Comment by ErinCain** [comment]
@thesadie Please review this pull request. This pull request fixes the issue of "Creator" vs "creator" input into metadata template spreadsheet. This is important because without the creator node the XML file generated is invalid.

**Comment by thesadie** [comment]
Please check if any tests need updating and rebuild the docs

**Comment by ErinCain** [comment]
I fixed the test and redid the documentation to account for the changes that I made in the add_personnel function to ensure that the package still functions and reflects my changes.

**Review by thesadie — APPROVED** [review]
Looks good, make a reminder someplace to run the pkgdown build before we make the main branch v0.1.1

**Pull request merged**
